# Generated by Django 3.1.5 on 2021-01-16 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
